version: 2
updates:
- package-ecosystem: nuget
  directory: "/src"
  schedule:
    interval: daily
    time: "02:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: Microsoft.Extensions.Logging.Abstractions
    versions:
    - "> 2.0.0"
  - dependency-name: Hangfire.Core
    versions:
    - 1.7.19
    - 1.7.20
    - 1.7.21
  - dependency-name: Hangfire.AspNetCore
    versions:
    - 1.7.19
    - 1.7.20
    - 1.7.21
  - dependency-name: Nuke.Common
    versions:
    - 5.0.2
    - 5.1.0
  - dependency-name: GitVersion.CommandLine
    versions:
    - 5.6.4
    - 5.6.5
    - 5.6.6
    - 5.6.7
  - dependency-name: MSTest.TestFramework
    versions:
    - 2.1.2
    - 2.2.1
    - 2.2.2
  - dependency-name: MSTest.TestAdapter
    versions:
    - 2.1.2
    - 2.2.1
    - 2.2.2
  - dependency-name: Microsoft.NET.Test.Sdk
    versions:
    - 16.8.3
    - 16.9.1
  - dependency-name: Newtonsoft.Json
    versions:
    - 12.0.3
