version: 1.0.{build}
pull_requests:
  do_not_increment_build_number: true
image: Visual Studio 2017
configuration: Release
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'
build_script:
- cmd: >-
    build.cmd

artifacts:
- path: 'output\*.nupkg'
  name: NuGet

deploy:
- provider: NuGet
  api_key:
    secure: ok2oM7BCMYFhta85N4Q7szqKoND6VUlzYAJtJGUMpVjGMrwmvSr0JT+ca4qttbwZ
  on:
    branch: master